[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/otiai10/copy"

[[constraint]]
  branch = "master"
  name = "github.com/tj/go-dropbox"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"
